Homework 07 is done
Ula1ri/python-developer-r_d_lectures pull request #12
Opened 2022-12-23 20:01 UTC by Ula1ri

2022-12-24 11:23 UTC, Ula1ri commented
Якщо не важко, поясніть мені чому цей шмат коду праює так само як той що я відвправив на перевірку
`    elif command == 'list':
        for key in phone_book.items():
            print(key)`
oсь з коду:
`    elif command == 'list':
        for item in phone_book:
            print(item)`
чи можливо обидва варіанти вірні?

2022-12-24 11:39 UTC, Ula1ri commented
aле час від часу якщо використовувати `elif command == 'list':
        for key in phone_book.items():
            print(key)`
программа друкує весь словник, як на скріні, дивна штука )))
![dict-items](https://user-images.githubusercontent.com/119409591/209434299-12a07507-3137-4457-8f2d-8088251d2ced.jpg)

2022-12-24 12:01 UTC, Ula1ri commented
Але в PyCharm працює корректно. VSCode некорректно інтерпритує? `elif command == 'list': for key in phone_book.keys(): print(key)` також в VSCode видає весь словник, як на скріні)) але якщо з допомогою программы перезаписувати словник, то все починає робити корректно.
Неяноно. 
Ймовірно, варто мати наувазі, що VSCode може виводити некоррекну інформацію. ))

2022-12-26 21:10 UTC, klymenok commented
> Якщо не важко, поясніть мені чому цей шмат коду праює так само як той що я відвправив на перевірку ` elif command == 'list': for key in phone_book.items(): print(key)` oсь з коду: ` elif command == 'list': for item in phone_book: print(item)` чи можливо обидва варіанти вірні?

По дефолту при ітеруванні по словнику ми ітеруємося за його ключами

2022-12-26 21:12 UTC, klymenok commented
> Але в PyCharm працює корректно. VSCode некорректно інтерпритує? `elif command == 'list': for key in phone_book.keys(): print(key)` також в VSCode видає весь словник, як на скріні)) але якщо з допомогою программы перезаписувати словник, то все починає робити корректно. Неяноно. Ймовірно, варто мати наувазі, що VSCode може виводити некоррекну інформацію. ))

Навряд чи справа у VS Code. Але так як ваш код не відповідає зараз прикладам, які у вас в коментарі, то мені важко сказати що з ним не так

2022-12-26 21:14 UTC, klymenok requested changes

2022-12-26 21:14 UTC, klymenok commented on Lecture_07/Homework_07.py
> +    name = split_input[1]
This will fail with `list` command

2022-12-26 21:14 UTC, klymenok commented on Lecture_07/Homework_07.py
> +    number = split_input[2]
This will fail with `list` command

2022-12-26 21:14 UTC, klymenok commented on Lecture_07/Homework_07.py
> +        phone_book[name] = number
It is forbidden to override records according to the task

2022-12-26 21:14 UTC, klymenok commented on Lecture_07/Homework_07.py
> +        print(phone_book[name])
It is better to check if key exists before accessing it

2022-12-27 20:17 UTC, klymenok requested changes

2022-12-27 20:17 UTC, klymenok commented on Lecture_07/Homework_07.py
> +        phone_book.update({name: number})
It is forbidden to override records according to the task

2022-12-27 21:42 UTC, Ula1ri commented
Я перепрошую, але я нерозумію, що я роблю не так. В наших матеріалах до лекцїї було цих два способи додавання  інформації в словник.  І якщо обидва хибні, значить я щось точно упускаю. Дякую за терпіння.

2023-01-06 19:46 UTC, klymenok commented
> Я перепрошую, але я нерозумію, що я роблю не так. В наших матеріалах до лекцїї було цих два способи додавання інформації в словник. І якщо обидва хибні, значить я щось точно упускаю. Дякую за терпіння.

Якщо ваш коментар стосується мого коментаря `It is forbidden to override records according to the task`, то суть не в тому, що ви додаєте до словника якось не так, а в тому, що згідно із завданням, ви не можете додавати до словника запис, якщо запис там вже є. Тобто вам потрібно зробити перевірку на наявність ключа в словнику, який ви збираєтеся додати, і тільки якщо ключа немає - додавати цей запис

2023-01-06 19:47 UTC, klymenok commented on Lecture_07/Homework_07.py
> +    name = split_input[1]
This still should be updated. Add some check here, like
```
if len(split_input > 1):
    name = split_input[1]

2023-01-06 19:47 UTC, klymenok commented on Lecture_07/Homework_07.py
> +    number = split_input[2]
This still should be updated. Add some check here, like
```
if len(split_input > 2):
    name = split_input[2]

2023-01-07 11:18 UTC, Ula1ri commented
Дякую за розяснення, я зрозумів свою помилку, чомусь мені здалося, що якщо ключ унікальний по своїй суті,  то його перезаписати неможливо. В останньому оновленні я додав перевірку ключа, тепер здається все, ще раз дякую, веселого Різьдва!

2023-01-11 22:32 UTC, klymenok requested changes
Додайте, будь ласка, зміни відповідно до моїх коментарів стосовно змінних name і number

2023-01-12 10:53 UTC, Ula1ri commented
Дякую за нагадування і пораду! Цей коментар сховався від мене за низкою інших і я ненароком його упустив. Я пробував сам цю кострукцію довести до пуття, але доствіду ще не достатньо, так що дякую двічі.

2023-01-12 22:06 UTC, klymenok approved these changes
Looks good!

2023-01-13 09:50 UTC, merged