Homework 11
Ula1ri/python-developer-r_d_lectures pull request #14
Opened 2023-01-16 11:53 UTC by Ula1ri

Доброго дня, минулого тижня я був хворий, здається грип, тому приступити до виконання ДЗ зміг тільки на вихідніх. І це завдання далось мені дуже складно . Мені здається, що без помилок в ньому не обійшлось, тому прошу, напишіть що не так, в трохи розгорнутішому вигляді, бо часом важко зорієнтуватися в тому що ще до кінця не освоїв. Дякую!

2023-01-17 00:00 UTC, klymenok requested changes

2023-01-17 00:00 UTC, klymenok commented on Lecture_11/Homework_11.py
> +        with MyContextManager() as file:
You don't use `file` variable, so you can skip it and use just `with MyContextManager():`

2023-01-17 00:00 UTC, klymenok commented on Lecture_11/Homework_11.py
> +    return wrap()
Do not call the wrapper since the code of the decorated function will be executed immediately

2023-01-17 00:00 UTC, klymenok commented on Lecture_11/Homework_11.py
> +            func()
Use `return` statement here to be able to decorate functions that return some value

2023-01-17 12:30 UTC, Ula1ri commented
Здається, поправив усе

2023-01-18 08:46 UTC, klymenok commented on Lecture_11/Homework_11.py
> +            return func
And here you should call the `func` and pass *args and **kwargs as parameters `return func(*args, **kwargs)`

2023-01-18 21:46 UTC, klymenok requested changes

2023-01-18 21:46 UTC, klymenok commented on Lecture_11/Homework_11.py
> +            raise MyCustomException('Custom exception is occurred')
This exception will never be raised here, you can delete it

2023-01-18 21:46 UTC, klymenok commented on Lecture_11/Homework_11.py
> +            func(*args, **kwargs)
You call here `func` and call it again at the next line. It shouldn't be like this. Remove this line

2023-01-21 17:45 UTC, klymenok approved these changes
Looks good!

2023-01-23 09:59 UTC, merged