Homework 12
Ula1ri/python-developer-r_d_lectures pull request #15
Opened 2023-01-18 14:59 UTC by Ula1ri

Доброго дня! Я все ще грипую і тема дається дуже важко, тому прошу, пишіть в більш розширеному вигляді, бо чим більше ми йдемо в глиб, тим менше я розумію що відбувається, дякую!

2023-01-21 15:33 UTC, acman requested changes
Overall looks good! Several changes are required to be submitted.

2023-01-21 15:33 UTC, acman commented on Lecture_12/Homework_12.py
> +        return func(*args, **kwargs)
there is no need to run the function several times 

```suggestion
        result = func(*args, **kwargs)
        return result
```

2023-01-21 15:33 UTC, acman commented on Lecture_12/Homework_12.py
> +with open('json_dict.txt',) as phone_data: #Зчитємо дані з файла
if data in the file has type `json` - the file name should use the extension` .json`
nit: good practice using comments: two spaces after code + # + space
nit: all time set in what `mode` you open file

```suggestion
with open('contacts.json', 'r') as phone_data:  # Зчитуємо дані з файла
```

2023-01-21 15:33 UTC, acman commented on Lecture_12/Homework_12.py
> +            print(f'\nFunction {open} is called at {datetime.now()}', file=log_file) # записуємо в log.txt виклик функції
> записувати в файл назву функції

I think you mean `{func}` instead `{open}`

2023-01-23 10:39 UTC, Ula1ri commented
Дякую за розгорнуту відповідь, це дуже спростило усвідомлення своїх помилок.

2023-01-23 20:03 UTC, acman approved these changes
👍

2023-01-24 11:01 UTC, merged