Homework 18
Ula1ri/python-developer-r_d_lectures pull request #17
Opened 2023-02-07 19:17 UTC by Ula1ri

Доброго дня,  робив все як вказано в завданні, але чомусь не спрацьовує, допоможіть зрозуміти, що я роблю не так, дякую!

2023-02-09 14:00 UTC, acman requested changes
Overall looks good but I think there was some misunderstanding about the task.

2023-02-09 14:00 UTC, acman commented on Lecture_18/Homework_18.py
> +        return Bot(self.say_name)
task was to print name here
```suggestion
        print(self.name)
```

2023-02-09 14:00 UTC, acman commented on Lecture_18/Homework_18.py
> +        return Bot(self.send_message())
```suggestion
        print(message)
```

2023-02-09 14:00 UTC, acman commented on Lecture_18/Homework_18.py
> +    def __init__(self, url, chat_id):
I think the task was to inherit `init` method
```suggestion
    def __init__(self, name, url=None, chat_id=None):
        super().__init__(name)
```

2023-02-09 14:00 UTC, acman commented on Lecture_18/Homework_18.py
> +        print(f'TG bot says{message} to chat {chat_id} using {url}')
this message should be printed in `send_massage` method
```suggestion
        print(f'TG bot says{message} to chat {self.chat_id} using {self.url}')
```

2023-02-09 14:59 UTC, Ula1ri commented
Я вніс указані вище правки, але є ще щось що я зробив не так як треба.

2023-02-10 13:03 UTC, acman requested changes
Almost there! I suggest it would be helpful for you to rewatch the video about class inheritance or revise the workbook about this topic and try to practice more.

2023-02-10 13:03 UTC, acman commented on Lecture_18/Homework_18.py
> +    def __init__(self, name,):
```suggestion
    def __init__(self, name):
```

2023-02-10 13:03 UTC, acman commented on Lecture_18/Homework_18.py
> +        return TelegramBot(self.send_message())
here method  `send_message` from `Bot` should be rewritten
```suggestion
        print(f'{self.name} bot says {message} to chat {self._chat_id} using {self._url}')
```

2023-02-10 13:03 UTC, acman commented on Lecture_18/Homework_18.py
> +        print(f'TG bot says{message} to chat {self.chat_id} using {self.url}')
remove this line here, it will be printed in `send_message`
```suggestion
```

2023-02-10 16:43 UTC, Ula1ri commented
Прошу вибачення за купу помилок, код тепер виконується але є питання. Щоб він спрацьовував я вказую в команді `some_bot.say_name() `в дужках ім'я классу. В іншому випадку   інтерпритатор видає помилку. Це так має бути, чи я щось роблю не так? Дякую за терпіння!

2023-02-11 13:16 UTC, acman requested changes
and final fixes :)

2023-02-11 13:16 UTC, acman commented on Lecture_18/Homework_18.py
> +    def say_name(self, name):
Aaah! here is the problem, method `say_name` waits `name` as required argument
```suggestion
    def say_name(self):
```

2023-02-11 13:16 UTC, acman commented on Lecture_18/Homework_18.py
> +some_bot.say_name(Bot)
```suggestion
some_bot.say_name()
```

2023-02-11 13:16 UTC, acman commented on Lecture_18/Homework_18.py
> +telegram_bot.say_name(TelegramBot)
```suggestion
telegram_bot.say_name()
```

2023-02-11 13:22 UTC, acman commented
> Прошу вибачення за купу помилок, код тепер виконується але є питання. Щоб він спрацьовував я вказую в команді `some_bot.say_name() `в дужках ім'я классу. В іншому випадку інтерпритатор видає помилку. Це так має бути, чи я щось роблю не так? Дякую за терпіння!

та все гуд, ви тут, щоб вчитися, треба просто більше практики роботи з класами
метод `say_name` чекає обов'язкового аргумента `name` але його не выкорыстовує, тому туди можна будьщо передати, не тільки ім'я классу. Треба цей аргумент видалити.

2023-02-12 12:47 UTC, Ula1ri commented
Тепер працює корректно, дякую за настанови!

2023-02-12 15:59 UTC, acman approved these changes

2023-02-13 10:15 UTC, merged