Homework lecture 3
Ula1ri/python-developer-r_d_lectures pull request #3
Opened 2022-12-06 18:25 UTC by Ula1ri

Домашнє завадання до третьої лекції

2022-12-06 21:08 UTC, klymenok requested changes
The code should be written in a file with .py extension. Please, update your PR

2022-12-06 21:08 UTC, klymenok commented on lecture3/Homework_lecture_3
> +print (r)
There shouldn't be a space in calling `print` function. Like this: print(r)

2022-12-06 21:08 UTC, klymenok commented on lecture3/Homework_lecture_3
> +a = '2'
Variables a, b, and c should have a type `int`, and variable d should be a string. Try to update your solution

2022-12-06 22:09 UTC, Ula1ri commented
Тепер здається правильно. Вибачаюсь, думав що 6 задача була просто головоломкою.

2022-12-07 21:25 UTC, klymenok commented
There is still one unfixed thing - The code should be written in a file with .py. Rename your file: `Homework_lecture_3` -> `Homework_lecture_3.py`

2022-12-07 21:56 UTC, Ula1ri commented
Здається цього разу уже все

2022-12-07 22:03 UTC, klymenok approved these changes
There is still Homework_lecture_3 file, but let's assume it is a file with comment 🙂

2022-12-07 22:34 UTC, Ula1ri commented
Тут сталося щось мені не зрозуміле. В цьому пулреквесті є тепер є два файли один старий, без розширення і новий з розширенням .py. На компютері файла без розширення уже нема, я його перейменував. І тут в бранці його також немає. Це баг, фантомний файл, чи я щось зробив не так?

2022-12-09 15:32 UTC, merged